# Generated by Django 3.2.18 on 2023-04-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('protagonists', models.TextField()),
                ('poster', models.ImageField(upload_to='posters')),
                ('start_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
    ]
